src/padron_web/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('padron/', include('votes.urls')),
    path('admin/', admin.site.urls),
]

src/votes/urls.py
from django.urls import path

from . import views
from .views import LoginView, NewVoterView, DeleteVoterView

urlpatterns = [
    path('votantes/', views.voters, name='voters'),
    path('votantes/<str:pk>/', views.voter_info, name='voter_info'),
    path('login/', LoginView.as_view(
         template_name='votes/login.html',
         redirect_authenticated_user=True),
         name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('gestion-votantes/agregar/', NewVoterView.as_view(
         template_name='votes/new_voter.html'),
         name='new_voter'),
    path('gestion-votantes/eliminar/<str:pk>', DeleteVoterView.as_view(), name='delete_voter')
]

src/votes/models.py
from django.db import models


class Location(models.Model):
    """
    Model for vote locations in Costa Rica.

    ...

    Attributes
    ----------
    elec_code : CharField
        location's electoral code. This is the primary key.
    province : CharField
        name of the province.
    canton : CharField
        name of the canton
    district : CharField
        name of the district

    Methods
    -------
    """
    elec_code = models.CharField('electoral code', max_length=200, primary_key=True)
    province = models.CharField(max_length=200)
    canton = models.CharField(max_length=200)
    district = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.district}, {self.canton}, {self.province}"

    class Meta:
        indexes = [
            models.Index(fields=['province']),
            models.Index(fields=['canton']),
            models.Index(fields=['district']),
        ]


class Person(models.Model):
    """
    Model for Costa Rican voters.

    ...

    Attributes
    ----------
    identification : CharField
        legal identification in Costa Rica
    elec_code : CharField
        foreign key of location model
    voting_board : CharField
        voting board within the vote location
    full_name : CharField
        person's full name
    gender : CharField
        person's gender. the person is a man if id's fourth digit is even, otherwise is a woman.

    Methods
    -------
    """
    identification = models.CharField(max_length=15, primary_key=True)
    elec_code = models.ForeignKey(Location, on_delete=models.CASCADE)
    voting_board = models.CharField(max_length=15)
    full_name = models.CharField('name', max_length=200)
    gender = models.CharField(max_length=200)
    id_expiration_date = models.DateField()

    def __str__(self):
        return f"Cedula: {self.identification}, {self.full_name}"

    class Meta:
        indexes = [
            models.Index(fields=['identification', 'elec_code', 'gender']),
            models.Index(fields=['identification', 'id_expiration_date']),
        ]

src/votes/forms.py
from django import forms
from votes.models import Person, Location


class SearchLocationForm(forms.Form):
    """
    A class for the searching form in /voters/ page

    ...

    Attributes
    ----------
    identification : CharField
        legal voter identification
    name : CharField
        the name of the voter
    """
    identification = forms.CharField(label='identification', max_length=20, required=False)
    name = forms.CharField(label='name', max_length=100, required=False)


class NewVoterForm(forms.ModelForm):
    """
    A class for the new voter information

    ...

    Attributes
    ----------
    identification : IntegerField
        legal voter identification as numbers
    elec_code : ModelChoiceField
        voter's electoral location
    full_name : CharField
        voter's full name
    id_expiration_date : DateField
        date of voter id's expiration
    """
    identification = forms.IntegerField(label='Identificación', required=True, widget=forms.NumberInput(
        attrs={'class': 'form-control me-2',
               'type': 'search',
               'aria-label': 'Search'}))

    elec_code = forms.ModelChoiceField(label='Lugar de votación', queryset=Location.objects.all(), widget=forms.Select(
        attrs={'class': 'form-control me-2',
               'type': 'search'}))

    full_name = forms.CharField(label='Nombre', required=True, widget=forms.TextInput(
        attrs=({'class': 'form-control me-2',
                'type': 'search',
                'aria-label': 'Search'})))

    id_expiration_date = forms.DateField(label='Fecha de vencimiento de la cédula', required=True,
                                         widget=forms.SelectDateWidget(
                                             attrs={'class': 'form-control me-2',
                                                    'type': 'search',
                                                    'aria-label': 'Search'}))

    class Meta:
        model = Person
        fields = ['identification', 'elec_code',
                  'full_name', 'id_expiration_date']

src/votes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView
from .forms import SearchLocationForm
from .models import Person
from votes.utils import set_database
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .forms import NewVoterForm


DATABASE = set_database()


def voters(request):
    """
    The voters view

    :param request: for html requests
    :return: the same view with the list of voters (if possible)
    """
    param_dict = {}

    if request.method == 'POST':
        form = SearchLocationForm(request.POST)

        if form.is_valid():
            identification = form.cleaned_data['identification']
            name = form.cleaned_data['name']

            voters_info_list = DATABASE.search_voters(identification=identification, name=name.upper())

            param_dict['voters_info_list'] = voters_info_list

    if request.user.is_authenticated:
        param_dict['logout'] = "Cerrar Sesión"

    return render(request, "votes/voters.html", param_dict)


def voter_info(request, pk):
    """
    The voter info view

    :param request: for html requests
    :param voter_id: the voter identification taken from the list
    :return: a view with voter info and some statistics related
    """
    param_dict = {}
    person = DATABASE.get_voter(pk)

    if person is not None:
        elec_code = person.elec_code
        statistics_list = DATABASE.get_voter_statistics(person.id_expiration_date, elec_code)

        param_dict['voter_info_list'] = [person]
        param_dict['statistics_list'] = statistics_list

    else:
        param_dict['error_message'] = 'Voter not found. Make sure the voter already exists.'

    if request.user.is_authenticated:
        param_dict['logout'] = "Cerrar Sesión"

    return render(request, "votes/voter_info.html", param_dict)


class UserLoginView(LoginView):
    """
    A user login view using Django's LoginView
    """
    redirect_authenticated_user = True


@login_required
def logout_view(request):
    """
    The view after the user logs out

    :param request: for html request
    :return: a view of logout message and redirection page
    """
    logout(request)
    return render(request, "votes/logout_view.html")


@method_decorator(login_required, name='dispatch')
class NewVoterView(CreateView):
    """
    A view with the form for new voters
    """
    model = Person
    form_class = NewVoterForm

    def form_valid(self, form):
        self.object = DATABASE.add_voter(form.cleaned_data)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('voter_info', kwargs={'pk': self.object})


@method_decorator(login_required, name='dispatch')
class DeleteVoterView(DeleteView):
    """
    A view to delete voters from database
    """
    model = Person

    def get_object(self, queryset=None):
        return DATABASE.get_voter(self.kwargs.get("pk"))

    def form_valid(self, form):
        success_url = self.get_success_url()
        DATABASE.delete_voter(self.object.pk)
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse('voters')

src/votes/templates/votes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'votes/base.css' %}">
    {% block head %}
    {% endblock head %}
</head>
<body>

    <nav class="navbar navbar-fixed-top navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'voters' %}">Votaciones</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'voters' %}">Inicio</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'voters' %}">¿Dónde debo votar?</a>
            </li>

            {% block extrali %}
            {% endblock extrali %}

          </ul>
        </div>

      </div>
    </nav>

    {% block body %}
    {% endblock body %}

</body>
</html>

src/votes/templates/votes/login.html
{% extends 'votes/base.html' %}

{% block title %} Iniciar Sesión {% endblock title %}

{% block body %}

<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <h3 class="mb-5">Iniciar Sesión</h3>
              <form method="post"> {% csrf_token %}
                <div class="form-outline mb-4">
                  <input id="text" class="form-control form-control-lg" placeholder="Username" name="username"/>
                </div>

                <div class="form-outline mb-4">
                  <input type="password" id="typePasswordX-2" class="form-control form-control-lg" placeholder="Contraseña" name="password"/>
                </div>

                <hr class="my-4">
                <button class="btn btn-outline-primary btn-lg btn-block" type="submit">Iniciar Sesión</button>
              </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock body %}

src/votes/templates/votes/logout_view.html
{% extends 'votes/base.html' %}

{% block title %} Cerrando Sesión {% endblock title %}

{% block body %}
<div class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Cerrando Sesión</h5>
        <p class="card-text">
            La sesión ha finalizado con éxito. Para volver al
            Menú de Inicio presione el botón 'Volver a Inicio':
        </p>

        <a href="{% url 'voters' %}" class="btn btn-outline-success">Volver a Inicio</a>
    </div>
</div>

{% endblock body %}

src/votes/templates/votes/new_voter.html
{% extends 'votes/base.html' %}

{% block title %} Agregar votante {% endblock title %}

{% block head %}
{% load static %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_elec_code').select2();
    });
</script>
{% endblock head %}

{% block extrali %}
    {% if perms.votes.add_person %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
        </li>
    {% endif %}
{% endblock extrali %}

{% block body %}
<br/><br/>

<div class="container">
    <form class="class=d-flex mb-3" method="post"> {% csrf_token %}
        {{ form }}
        <button class="btn btn-outline-success" type="submit">Agregar</button>
    </form>
</div>
{% endblock body %}

src/votes/templates/votes/person_confirm_delete.html
{% extends 'votes/base.html' %}

{% block title %} Eliminar votante {% endblock title %}

{% block extrali %}
    {% if perms.votes.add_person %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
        </li>
    {% endif %}
{% endblock extrali %}

{% block body %}
<br/><br/><br/>
<div class="container">
<p class="h4">¿Desea eliminar a {{ object.full_name }}, Cédula: {{ object.identification }} de la lista de votantes?</p>
    <br/>
<form class="d-flex mb-3 " method="post">
    {% csrf_token %}
    <button class="btn btn-danger" type="submit">Confirmar</button>
    <a href="{% url 'voters' %}">
    <button type="button" class="btn btn-outline-dark" style="margin-left: 25px">Cancelar</button>
</a>
</form>

</div>
{% endblock body %}

src/votes/templates/votes/voter_info.html
{% extends 'votes/base.html' %}

{% block title %} Información de votante {% endblock title %}

    {% block extrali %}
    {% if perms.votes.add_person %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
        </li>
    {% endif %}
    {% endblock extrali %}

{% block body %}
<div class="container my-3">

  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">

      {% if error_message %}
        <div class="alert alert-warning d-flex align-items-center" role="alert">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
          </svg>
        <div>
          {{ error_message }}
        </div>
        </div>
      {% endif %}

      {% if voter_info_list %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Cédula</th>
              <th scope="col">Nombre</th>
              <th scope="col">Lugar de votación</th>
              <th scope="col">Mesa de votación</th>
              <th scope="col">Vencimiento de la cédula</th>
            </tr>
          </thead>

          <tbody>
            {% for voter in voter_info_list %}
              <tr>
                <td>{{ voter.identification }}</td>
                <td>{{ voter.full_name }}</td>
                <td>{{ voter.elec_code }}</td>
                <td>{{ voter.voting_board }}</td>
                <td>{{ voter.id_expiration_date }}</td>
              </tr>
            {% endfor %}
          </tbody>

        </table>
      {% endif %}

      {% if statistics_list %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Votantes Por Distrito</th>
              <th scope="col">Votantes Por Cantón</th>
              <th scope="col">Votantes Por Provincia</th>
              <th scope="col">Hombres por Distrito</th>
              <th scope="col">Hombres por Cantón</th>
              <th scope="col">Hombres por Provincia</th>
              <th scope="col">Mujeres por Distrito</th>
              <th scope="col">Mujeres por Cantón</th>
              <th scope="col">Mujeres por Provincia</th>
              <th scope="col">Votantes con misma fecha de vencimiento</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              {% for count in statistics_list %}
                <td>{{ count }}</td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
      {% endif %}
    </div>
  </nav>
</div>

{% endblock body %}

src/votes/templates/votes/voters.html
{% extends 'votes/base.html' %}

{% block title %} Lista de votantes {% endblock title %}

    {% block extrali %}
    {% if perms.votes.add_person %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
        </li>
    {% endif %}
    {% endblock extrali %}


{% block body %}
<div class="container my-3">

    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="container-fluid row p-0" style="vertical-align:top">

            <div class="col">
                <form class="d-flex mb-3 " method="post"> {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Numero de cédula" aria-label="Search" name="identification">
                    <input class="form-control me-2" type="search" placeholder="Nombre" aria-label="Search" name="name">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
            </div>

            <div class="col d-flex justify-content-end">
                {% if perms.votes.add_person %}
                <a class="align-items-end " href="{% url 'new_voter' %}">
                    <button class="btn btn-outline-primary" style="btn-padding-y: 0%">Agregar votante</button>
                </a>
                {% endif %}
            </div>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Cédula</th>
                    <th scope="col">Nombre</th>
                    <th scope="col"></th>
                </tr>
            </thead>

            {% if voters_info_list %}
                <tbody>
                    {% for voter in voters_info_list %}
                        <tr>
                            <td>
                                <a href="{{ voter.identification }}/">
                                    {{ voter.identification }}
                                </a>
                            </td>
                            <td>{{ voter.full_name }}</td>
                            <td>
                                {% if perms.votes.delete_person %}
                                <a href="{% url 'delete_voter' pk=voter.identification %}">
                                    <button class="btn btn-danger">Eliminar votante</button>
                                </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            {% endif %}
        </table>

      </div>
    </nav>

</div>

{% endblock body %}